import { Project } from '../types/models';

export const projects: Project[] = [
  {
    id: 0,
    name: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, nobis, possimus? Dolor ipsam repudiandae veritatis',
    description: 'Lorem ipsum dolor sit amet.',
    cost: 500,
    collectedDonation: 70,
    image: 'https://placekitten.com/640/360',
    country: 'Egypt',
    executionDuration: '3 Months',
    startAt: new Date('02/25/2019'),
    endAt: new Date('10/27/2019'),
    cause: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, nobis, possimus? Dolor ipsam repudiandae veritatis?',
    result: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, nobis, possimus? Dolor ipsam repudiandae veritatis?',
    village: 'Solem',
    projectCategory: 'cat #1',
    isCostCollectedDone: false,
    isExecutionDone: false,
  },
  {
    id: 1,
    name: 'Make new hospital #2',
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, nobis, possimus? Dolor ipsam repudiandae veritatis?',
    cost: 500,
    collectedDonation: 370,
    image: 'https://placekitten.com/640/360',
    country: 'Egypt',
    executionDuration: '3 Months',
    startAt: new Date('02/25/2019'),
    endAt: new Date('10/27/2019'),
    cause: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, nobis, possimus? Dolor ipsam repudiandae veritatis?',
    result: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, nobis, possimus? Dolor ipsam repudiandae veritatis?',
    village: 'Solem',
    projectCategory: 'cat #1',
    isCostCollectedDone: false,
    isExecutionDone: false,
  },
  {
    id: 2,
    name: 'Make new hospital #3',
    description: 'Lorem ipsum dolor sit amet.', cost: 500,
    collectedDonation: 500,
    image: 'https://placekitten.com/640/360',
    country: 'Egypt',
    executionDuration: '3 Months',
    startAt: new Date('02/25/2019'),
    endAt: new Date('10/27/2019'),
    cause: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, nobis, possimus? Dolor ipsam repudiandae veritatis?',
    result: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, nobis, possimus? Dolor ipsam repudiandae veritatis?',
    village: 'Solem',
    projectCategory: 'cat #1',
    isCostCollectedDone: true,
    isExecutionDone: false,
  },
  {
    id: 3,
    name: 'Make new hospital #4',
    description: 'Lorem ipsum dolor sit amet.',
    cost: 500,
    collectedDonation: 500,
    image: 'https://placekitten.com/640/360',
    country: 'Egypt',
    executionDuration: '3 Months',
    startAt: new Date('02/25/2019'),
    endAt: new Date('10/27/2019'),
    cause: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, nobis, possimus? Dolor ipsam repudiandae veritatis?',
    result: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, nobis, possimus? Dolor ipsam repudiandae veritatis?',
    village: 'Solem',
    projectCategory: 'cat #1',
    isCostCollectedDone: true,
    isExecutionDone: true,
  },
  {
    id: 4,
    name: 'Make new hospital #5',
    description: 'Lorem ipsum dolor sit amet.',
    cost: 500,
    collectedDonation: 400,
    image: 'https://placekitten.com/640/360',
    country: 'Egypt',
    executionDuration: '3 Months',
    startAt: new Date('02/25/2019'),
    endAt: new Date('10/27/2019'),
    cause: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, nobis, possimus? Dolor ipsam repudiandae veritatis?',
    result: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, nobis, possimus? Dolor ipsam repudiandae veritatis?',
    village: 'Solem',
    projectCategory: 'cat #1',
    isCostCollectedDone: false,
    isExecutionDone: false,
  },
  {
    id: 5,
    name: 'عمل مستشفى جديد #6',
    description: 'للمهتمين قمنا بوضع نص لوريم إبسوم القياسي والمُستخدم منذ القرن الخامس عشر في الأسفل. وتم أيضاً توفير الأقسام 1.10.32 و 1.10.33 من \"حول أقاصي الخير والشر\" (de Finibus Bonorum et Malorum) لمؤلفه شيشيرون (Cicero) بصيغها الأصلية، مرفقة بالنسخ الإنكليزية لها والتي قام بترجمتها هـ.راكهام (H. Rackham) في عام 1914',
    cost: 700,
    collectedDonation: 400,
    image: 'https://placekitten.com/640/360',
    country: 'Egypt',
    executionDuration: '3 Months',
    startAt: new Date('02/25/2019'),
    endAt: new Date('10/27/2019'),
    cause: 'للمهتمين قمنا بوضع نص لوريم إبسوم القياسي والمُستخدم منذ القرن الخامس عشر في الأسفل. وتم أيضاً توفير الأقسام 1.10.32 و 1.10.33 من \"حول أقاصي الخير والشر\" (de Finibus Bonorum et Malorum) لمؤلفه شيشيرون (Cicero) بصيغها الأصلية، مرفقة بالنسخ الإنكليزية لها والتي قام بترجمتها هـ.راكهام (H. Rackham) في عام 1914',
    result: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, nobis, possimus? Dolor ipsam repudiandae veritatis?',
    village: 'Solem',
    projectCategory: 'cat #1',
    isCostCollectedDone: false,
    isExecutionDone: false,
  },
  {
    id: 6,
    name: 'عمل مستشفى جديد #7',
    description: 'للمهتمين قمنا بوضع نص لوريم إبسوم القياسي والمُستخدم منذ القرن الخامس عشر في الأسفل. وتم أيضاً توفير الأقسام 1.10.32 و 1.10.33 من \"حول أقاصي الخير والشر\" (de Finibus Bonorum et Malorum) لمؤلفه شيشيرون (Cicero) بصيغها الأصلية، مرفقة بالنسخ الإنكليزية لها والتي قام بترجمتها هـ.راكهام (H. Rackham) في عام 1914',
    cost: 150,
    collectedDonation: 90,
    image: 'https://placekitten.com/640/360',
    country: 'Egypt',
    executionDuration: '3 Months',
    startAt: new Date('02/25/2019'),
    endAt: new Date('10/27/2019'),
    cause: 'للمهتمين قمنا بوضع نص لوريم إبسوم القياسي والمُستخدم منذ القرن الخامس عشر في الأسفل. وتم أيضاً توفير الأقسام 1.10.32 و 1.10.33 من \"حول أقاصي الخير والشر\" (de Finibus Bonorum et Malorum) لمؤلفه شيشيرون (Cicero) بصيغها الأصلية، مرفقة بالنسخ الإنكليزية لها والتي قام بترجمتها هـ.راكهام (H. Rackham) في عام 1914',
    result: 'للمهتمين قمنا بوضع نص لوريم إبسوم القياسي والمُستخدم منذ القرن الخامس عشر في الأسفل. وتم أيضاً توفير الأقسام 1.10.32 و 1.10.33 من \"حول أقاصي الخير والشر\" (de Finibus Bonorum et Malorum) لمؤلفه شيشيرون (Cicero) بصيغها الأصلية، مرفقة بالنسخ الإنكليزية لها والتي قام بترجمتها هـ.راكهام (H. Rackham) في عام 1914',
    village: 'Solem',
    projectCategory: 'cat #1',
    isCostCollectedDone: false,
    isExecutionDone: false,
  },
  {
    id: 7,
    name: 'Make new hospital #8',
    description: 'Lorem ipsum dolor sit amet.',
    cost: 800,
    collectedDonation: 764,
    image: 'https://placekitten.com/640/360',
    country: 'Egypt',
    executionDuration: '3 Months',
    startAt: new Date('02/25/2019'),
    endAt: new Date('10/27/2019'),
    cause: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, nobis, possimus? Dolor ipsam repudiandae veritatis?',
    result: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, nobis, possimus? Dolor ipsam repudiandae veritatis?',
    village: 'Solem',
    projectCategory: 'cat #1',
    isCostCollectedDone: false,
    isExecutionDone: false,
  },
  {
    id: 8,
    name: 'Make new hospital #9',
    description: 'Lorem ipsum dolor sit amet.',
    cost: 500,
    collectedDonation: 356,
    image: 'https://placekitten.com/640/360',
    country: 'Egypt',
    executionDuration: '3 Months',
    startAt: new Date('02/25/2019'),
    endAt: new Date('10/27/2019'),
    cause: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, nobis, possimus? Dolor ipsam repudiandae veritatis?',
    result: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, nobis, possimus? Dolor ipsam repudiandae veritatis?',
    village: 'Solem',
    projectCategory: 'cat #1',
    isCostCollectedDone: false,
    isExecutionDone: false,
  },
  {
    id: 9,
    name: 'Make new hospital #10',
    description: 'Lorem ipsum dolor sit amet.',
    cost: 500,
    collectedDonation: 321,
    image: 'https://placekitten.com/640/360',
    country: 'Egypt',
    executionDuration: '3 Months',
    startAt: new Date('02/25/2019'),
    endAt: new Date('10/27/2019'),
    cause: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, nobis, possimus? Dolor ipsam repudiandae veritatis?',
    result: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, nobis, possimus? Dolor ipsam repudiandae veritatis?',
    village: 'Solem',
    projectCategory: 'cat #1',
    isCostCollectedDone: false,
    isExecutionDone: false,
  },
];