export const navigationConstants = {
  SCREEN_PARAM_PROJECT: 'SCREEN_PARAM_PROJECT',
  SCREEN_PARAM_RELATED_PROJECT_TYPE: 'SCREEN_PARAM_RELATED_PROJECT_TYPE',
  SCREEN_HOME: 'SCREEN_HOME',
  SCREEN_PROJECT_DETAILS: 'SCREEN_PROJECT_DETAILS',
  SCREEN_RELATED_PROJECTS: 'SCREEN_RELATED_PROJECTS',
  SCREEN_DONATE_FORM: 'SCREEN_DONATE_FORM',
  SCREEN_DRAWER_NAVIGATOR: 'SCREEN_DRAWER_NAVIGATOR',
  SCREEN_DONATION_PROJECTS: 'SCREEN_DONATION_PROJECTS',
  SCREEN_EXECUTION_PROJECTS: 'SCREEN_EXECUTION_PROJECTS',
  SCREEN_DONE_PROJECTS: 'SCREEN_DONE_PROJECTS',
  SCREEN_SETTINGS: 'SCREEN_SETTINGS',
};