export const navigationConstants = {
  SCREEN_PARAM_PROJECT: 'SCREEN_PARAM_PROJECT',
  SCREEN_HOME: 'SCREEN_HOME',
  SCREEN_PROJECT_DETAILS: 'SCREEN_PROJECT_DETAILS',
  SCREEN_RELATED_PROJECTS: 'SCREEN_RELATED_PROJECTS',
  SCREEN_DONATE_FORM: 'SCREEN_DONATE_FORM',
  SCREEN_DRAWER_NAVIGATOR: 'SCREEN_DRAWER_NAVIGATOR'
};