export const projectsActionsConstants = {
  GET_DONATION_PROJECTS:'GET_DONATION_PROJECTS',
  GET_EXECUTION_PROJECTS: 'GET_EXECUTION_PROJECTS',
  GET_DONE_PROJECTS: 'GET_DONE_PROJECTS',
  GET_ALL_PROJECTS: 'GET_ALL_PROJECTS'
};