export const projectsActionsConstants = {
  GET_DONATION_PROJECTS: 'GET_DONATION_PROJECTS',
  GET_EXECUTION_PROJECTS: 'GET_EXECUTION_PROJECTS',
  GET_DONE_PROJECTS: 'GET_DONE_PROJECTS',
  GET_ALL_PROJECTS: 'GET_ALL_PROJECTS',
  GET_PROJECT_CATEGORIES: 'GET_PROJECT_CATEGORIES',
  CHANGE_ACTIVE_CATEGORY: 'CHANGE_ACTIVE_CATEGORY'
};